USE Estados

CREATE TABLE Superficie_Estado(
ID_Estado INT NOT NULL IDENTITY PRIMARY KEY,
Superficie INTEGER NOT NULL,
Abreviacion VARCHAR(10) NULL,
Pais VARCHAR(50) NULL,
ID_Pais INT NOT NULL FOREIGN KEY REFERENCES PAIS(ID)
);

SELECT * FROM Superficie_Estado