CREATE TABLE [dbo].[Datos_Censo] (
[Rank] INT NOT NULL IDENTITY PRIMARY KEY,
[ID_Ciudad] INT NOT NULL FOREIGN KEY REFERENCES Ciudades_USA(ID_Ciudad),
[2020 Censo] INTEGER NULL,
[2010 Censo] INTEGER NULL
);