
-- AL IMPORTAR LA TABLA Superficie_Estados de excel, MODIFICAR LA QUERY POR ESTE:
/*
CREATE TABLE [dbo].[Superficie_Estado$] (
[ID_Estado] INT NOT NULL,
[Superficie] INTEGER NULL,
[Abreviacion] VARCHAR(10) NULL,
[Pais] VARCHAR(50) NULL,
[ID_Pais] INT NOT NULL
)
*/
-- UNA VEZ CREADA LA TABLA JUNTO CON SUS DATOS,
-- MODIFICO(O AGREGO) LAS CLAVES EN LAS CORRESPONDIENTES COLUMNAS
ALTER TABLE Superficie_Estado
 ADD PRIMARY KEY(ID_Estado);

ALTER TABLE Superficie_Estado
 ADD FOREIGN KEY (ID_Pais) REFERENCES PAIS(ID);